version: '3'
services:
  php:
    build: 
      context: ./docker/php
      dockerfile: Dockerfile.laravel-backend # Dockerfileの名前を指定
    volumes:
      - ./laravel-src:/var/www/html # srcフォルダをコンテナ内の/var/www/htmlにバインド
    ports:
      - "9000:9000"
  nginx:
      build:
        context: ./docker/nginx
        dockerfile: Dockerfile-nginx
      volumes:
        - /home/sd2kodama/ReduxPractice/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - /home/sd2kodama/ReduxPractice/docker/nginx/debug.log:/var/log/nginx/access_custom.log
      ports:
        - "8080:80"
      depends_on:
        - php
# MySQLなどの他のサービスもここに定義します