version: '3'
services:
  php:
    build: 
      context: ./docker/php
      dockerfile: Dockerfile.laravel-backend
    volumes:
      - ./laravel-src:/var/www/html 
    ports:
      - "9000:9000"
    networks:
     - mysql_bridge

  nginx:
      build:
        context: ./docker/nginx
        dockerfile: Dockerfile-nginx
      volumes:
        - /home/sd2kodama/ReduxPractice/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - /home/sd2kodama/ReduxPractice/docker/nginx/debug.log:/var/log/nginx/access_custom.log
      ports:
        - "8080:80"
      depends_on:
        - php

  mysql:
    container_name: mysql_host
    build: 
      context: ./docker/mysql
      dockerfile: Dockerfile-mysql
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user_name
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./docker/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
#      - ./docker/mysql/mysql_data:/var/lib/mysql
    restart: always
    platform: linux/amd64
    networks:
      - mysql_bridge

  phpmyadmin:
    container_name: phpmyadmin_host
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80" #localhost:8090 で phpMyAdmin にアクセスできます
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_host
      PMA_USER: user_name
      PMA_PASSWORD: password
    networks:
      - mysql_bridge

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  mysql_bridge:
    driver: bridge